# Generated by Django 5.0.6 on 2026-09-15 17:53

from django.db import migrations, models


# 机构编号回填表。
#
# 背景：种子数据（seed_data）早期用 name 作为 get_or_create 的去重键，
# 而 name 是可在界面上修改的展示字段。区县/机构被改名后，每次执行
# seed_data 都会再插入一套同名机构，现场库里已经出现了孤儿的重复捕捉点。
# 引入稳定的 code 字段后，种子数据改按 code 幂等匹配。
#
# 回填策略：优先按当前（襄阳市）名称匹配；匹配不到再退回历史（北京市）
# 名称，且同一 code 只回填一次——若库里新旧两套机构并存，新名称优先，
# 旧名称那套保持 code 为空，交由运维人工确认后清理（迁移不删业务数据）。
CURRENT_NAMES = [
    ('襄城流浪动物捕捉点', 'I001'),
    ('樊城流浪动物捕捉点', 'I002'),
    ('爱心宠物医院', 'I003'),
    ('瑞鹏宠物医院', 'I004'),
    ('芭比堂动物医院', 'I005'),
    ('宠安宠物诊所', 'I006'),
    ('阳光花园小区', 'C001'),
    ('翠湖天地小区', 'C002'),
    ('中关村南区', 'C003'),
    ('西单美居', 'C004'),
]

LEGACY_NAMES = [
    ('朝阳区流浪动物捕捉点', 'I001'),
    ('海淀区流浪动物捕捉点', 'I002'),
]


def backfill_institution_code(apps, schema_editor):
    Institution = apps.get_model('core', 'Institution')
    taken = set(
        Institution.objects.exclude(code__isnull=True).values_list('code', flat=True)
    )

    for mapping in (CURRENT_NAMES, LEGACY_NAMES):
        for name, code in mapping:
            if code in taken:
                continue
            inst = Institution.objects.filter(name=name, code__isnull=True).first()
            if inst is None:
                continue
            inst.code = code
            inst.save(update_fields=['code'])
            taken.add(code)


def unbackfill_institution_code(apps, schema_editor):
    Institution = apps.get_model('core', 'Institution')
    Institution.objects.update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_district_is_city_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='机构编号'),
        ),
        migrations.RunPython(backfill_institution_code, unbackfill_institution_code),
    ]
