# Generated by Django 5.0.6 on 2026-09-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user_name', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人姓名')),
                ('role', models.CharField(blank=True, default='', max_length=32, verbose_name='操作人角色')),
                ('district_name', models.CharField(blank=True, default='', max_length=50, verbose_name='区县名称快照')),
                ('module', models.CharField(blank=True, default='', max_length=64, verbose_name='业务模块')),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '修改'), (3, '删除')], default=2, verbose_name='操作类型')),
                ('object_type', models.CharField(blank=True, default='', max_length=64, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=200, verbose_name='对象标识')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='操作摘要')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('method', models.CharField(blank=True, default='', max_length=8, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='请求路径')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源IP')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.district', verbose_name='归属区县')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-action_time', '-id'],
                'indexes': [models.Index(fields=['-action_time'], name='audit_time_idx'), models.Index(fields=['district', '-action_time'], name='audit_dist_time_idx')],
            },
        ),
    ]
