# Generated by Django 5.0.6 on 2026-09-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', '平台管理员'), ('gov_city', '市级政府管理员'), ('gov_district', '区级政府管理员'), ('shelter', '捕捉点操作员'), ('hospital', '医院操作员'), ('adopter', '领养人')], default='adopter', max_length=20, verbose_name='角色'),
        ),
    ]
