# Generated by Django 5.0.6 on 2026-09-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='geo_address',
            field=models.CharField(blank=True, default='', help_text='由定位经纬度逆地理编码得到的地址名称', max_length=255, verbose_name='定位地址'),
        ),
        migrations.AddField(
            model_name='capture',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='capture',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
