# Generated by Django 5.0.6 on 2026-09-15 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_capture_status(apps, schema_editor):
    """历史数据状态回填。

    旧版本把所有捕捉单一律写成 completed，与真实转运情况无关。
    这里按「本单宠物是否已提交未被退回的转运单」重新推导：
    - 无有效转运单            → pending  待转运
    - 部分宠物已提交转运单    → partial  部分转运
    - 全部宠物已提交转运单    → completed 已完成
    """
    Capture = apps.get_model('business', 'Capture')
    Pet = apps.get_model('business', 'Pet')
    Transfer = apps.get_model('business', 'Transfer')

    active_codes = set()
    for t in Transfer.objects.filter(status__in=('pending', 'received')):
        for code in (t.pet_codes or '').split(','):
            code = code.strip()
            if code:
                active_codes.add(code)

    codes_by_capture = {}
    for cap_id, code in Pet.objects.values_list('capture_id', 'code'):
        if cap_id:
            codes_by_capture.setdefault(cap_id, set()).add(code)

    for capture in Capture.objects.all():
        codes = codes_by_capture.get(capture.id, set())
        total = len(codes)
        transferred = len(codes & active_codes)
        if total == 0 or transferred == 0:
            new_status = 'pending'
        elif transferred < total:
            new_status = 'partial'
        else:
            new_status = 'completed'
        if capture.status != new_status:
            capture.status = new_status
            capture.save(update_fields=['status'])


def _noop_reverse(apps, schema_editor):
    """状态为派生字段，回滚时无需还原历史值。"""


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_capture_geo_address_capture_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='capture',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_captures', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='capture',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='capture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='pet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo_capture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='捕捉照片'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='status',
            field=models.CharField(choices=[('pending', '待转运'), ('partial', '部分转运'), ('completed', '已完成'), ('void', '已作废')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.RunPython(_backfill_capture_status, _noop_reverse),
    ]
