# Generated by Django 5.0.6 on 2026-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_capture_deleted_at_capture_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='移出时间'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已移出'),
        ),
    ]
