# Generated by Django 5.0.6 on 2026-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_rename_dongjing_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerreturn',
            name='owner_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='主人住址'),
        ),
        migrations.AddField(
            model_name='ownerreturn',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回收时间'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', '待签收'), ('received', '已签收'), ('rejected', '已驳回'), ('void', '已撤回')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
