# Generated by Django 5.0.6 on 2026-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_ownerreturn_owner_address_ownerreturn_return_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('in_transit', '在途'), ('in_treatment', '待诊疗'), ('pending_adopt', '待领养'), ('pending_claim', '待领出'), ('adopted', '已领养'), ('released', '已放养'), ('euthanized', '已死亡'), ('owner_returned', '主人领回')], default='in_transit', max_length=20, verbose_name='状态'),
        ),
    ]
