# Generated by Django 5.0.6 on 2026-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
