# Generated by Django 5.0.6 on 2026-09-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_register_checkin_reminder_schedule'),
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.district', verbose_name='所属区县'),
        ),
    ]
