# Generated by Django 5.0.6 on 2026-09-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_message_district'),
        ('core', '0005_institution_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_txns', to='core.institution', verbose_name='库存归属机构'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_txns', to='core.institution', verbose_name='对方机构'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='type',
            field=models.CharField(choices=[('purchase', '采购入库'), ('dispatch', '下发'), ('receive', '签收'), ('consume', '消耗'), ('adjustment', '异动')], max_length=20, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='当前库存')),
                ('opening_quantity', models.IntegerField(default=0, verbose_name='期初库存')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stocks', to='core.institution', verbose_name='持有机构')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='business.material', verbose_name='物资')),
            ],
            options={
                'verbose_name': '机构库存',
                'verbose_name_plural': '机构库存',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.UniqueConstraint(fields=('material', 'institution'), name='uniq_material_institution_stock'),
        ),
    ]
