# Generated by Django 5.0.6 on 2026-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_backfill_material_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-id'], 'verbose_name': '放归记录', 'verbose_name_plural': '放归记录'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('in_transit', '在途'), ('in_treatment', '待诊疗'), ('pending_adopt', '待领养'), ('pending_claim', '待领出'), ('adopted', '已领养'), ('released', '已放归'), ('euthanized', '已死亡'), ('owner_returned', '主人领回')], default='in_transit', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='release',
            name='released_at',
            field=models.DateField(blank=True, null=True, verbose_name='放归日期'),
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('pending', '待放归'), ('released', '已放归')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
