# Generated by Django 5.0.6 on 2026-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_alter_release_options_alter_pet_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8, verbose_name='单据类型码')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份（后两位）')),
                ('last_no', models.IntegerField(default=0, verbose_name='已发流水号')),
            ],
            options={
                'verbose_name': '单据号计数器',
                'verbose_name_plural': '单据号计数器',
            },
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='ref_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='关联单据号'),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('prefix', 'year'), name='uniq_docseq_prefix_year'),
        ),
    ]
